# Autor: Paula Guerrero
# Fecha: 29/05/26
# Descripción: Archivo de configuración para SonarQube en el proyecto ScheduleClass Backend.
#              Define las propiedades necesarias para ejecutar el análisis de calidad
#              sobre el código fuente y las pruebas del backend desarrollado en Java

sonar.projectKey=scheduleclass-backend
sonar.projectName=ScheduleClass Backend
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_974253884af31d6d5eb16ab39cc578ee2c416289